FROM node:22-alpine3.18 AS builder

WORKDIR /usr/src/app

RUN apk add --no-cache bash libc6-compat openssl

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN npm run build

FROM node:22-alpine3.18 AS runtime

WORKDIR /usr/src/app

RUN apk add --no-cache bash libc6-compat openssl

COPY --from=builder /usr/src/app/package*.json ./

RUN npm install --omit=dev && npm cache clean --force

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/doc ./doc 

EXPOSE $PORT

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && node dist/main.js"]
