FROM node:22-alpine3.18

WORKDIR /usr/src/app

RUN apk add --no-cache openssl libc6-compat bash

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE $PORT

CMD ["sh", "-c", "npm run start:prisma:dev"]
