FROM node:22-alpine3.18

WORKDIR /usr/src/app

RUN apk add --no-cache openssl libc6-compat bash

COPY package*.json ./

RUN npm ci

COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY test ./test
COPY jest.config.json ./
COPY .prettierrc ./
COPY .eslintrc.js ./
COPY prisma ./prisma
COPY doc ./doc

EXPOSE $PORT

CMD ["sh", "-c", "npm run start:prisma:dev"]
